#!/bin/bash
# get script absolute path
BASE_DIR=$(cd $(dirname ${BASH_SOURCE[0]}) &>/dev/null && pwd)
CONFIG_FILE=$BASE_DIR/config/otter.yaml

# include lib
source $BASE_DIR/scripts/libotter.sh

# print logo 
logo

function otterctl_useage(){
    echo 1
}

case $1 in
"start")
    otterctl_useage
;;
"stop")
    otterctl_useage
;;
*)
    otterctl_useage
;;
esac