#!/bin/bash

# get script absolute path
BASE_DIR=$(cd $(dirname ${BASH_SOURCE[0]}) &>/dev/null && pwd)
CONFIG_FILE=$BASE_DIR/config/otter.yaml

# include lib
source $BASE_DIR/scripts/libotter.sh

# include download resource lib
source $BASE_DIR/scripts/libotter_download.sh

# include docker lib
source $BASE_DIR/scripts/libotter_docker.sh

# include ssh lib
source $BASE_DIR/scripts/libotter_ssh.sh

# include containerd lib
source $BASE_DIR/scripts/libotter_containerd.sh

# print logo
logo

function usage(){
    echo 1
}