## todo: 待测试某个节点网络不通，是否自动分发
- name: CHECK NODE NETWORK HEALTH
  shell: |
    { ping -c 3 -W 1 -i 0.1 8.8.8.8 &>/dev/null || ping -c 3 -W 1 -i 0.1 114.114.114.114 &>/dev/null ;} && exit 0
  register: NETWORK_HEALTH

#- name: debug
#  debug: msg={{ NETWORK_HEALTH.rc }}