## todo: 待测试某个节点网络不通，是否自动分发
- name: CHECK NODE NETWORK HEALTH
  shell: |
    {% for x in (IP_CHECK + DNS_CHECK) %}
      { ping -c 3 -W 1 -i 0.1 {{ x }} &>/dev/null || exit 1 ;}
    {% endfor %}
  register: NETWORK_HEALTH

#- name: debug
#  debug: msg={{ NETWORK_HEALTH.rc }}