#################################### otter 自动部署工具配置文件  ################
# 安装方式(online|offline)
OTTER_INSTALL_METHOD: online

# 是否启用混合架构部署(如果启用,离线下载时将会下载多架构二进制命令与镜像)
OTTER_MIXED_ENABLED: false

##################################  Chronyd 时间同步设置 ###########################
## 时间同步服务器IPS,如果有多个请填多个
# eg: TIME_SERVER: ["localhost"] TIME_SERVER: ["localhost","127.0.0.1"]
TIME_SERVER: ["localhost","127.0.0.1"]

##################################  RunTime 配置 #################################
# runtime 选择，目前只支持docker，未适配containerd
RUN_TIME_TYPE: docker

##################################  Docker 配置  #################################
# Docker版本,已验证版本: 20.10.24
DOCKER_VERSION: 20.10.24

# Docker 数据目录
DOCKER_ROOT_DATA: /var/lib/docker

# Docker driver版本(systemd|cgroupfs)
DOCKER_DRIVER: systemd

# docker网段设置(如有网络冲突，可自行修改,一般默认即可)
DOCKER_BIP: 192.168.244.1/24

################################ Containerd 配置 #################################


################################ Harbor 配置  ####################################
# 是否部署HARBOR，HARBOR部署方式为Chart部署
HARBOR_ENABLE: true

# HARBOR 部署节点IP，该IP必须要是K8S集群内
HARBOR_IP: x.x.x.x

# Harbor admin登陆密码
HARBOR_PASSWORD: Otter007

# Harbor 数据目录
HARBOR_DATA_PATH: /data/harbor