#################################### otter 自动部署工具配置文件  ################
# 安装方式(online|offline)
OTTER_INSTALL_METHO: online

# 是否启用混合架构部署(如果启用,离线下载时将会下载多架构二进制命令与镜像)
# 如果集群内有多架构请设置为true，否则会导致节点无法获取离线资源包
OTTER_MIXED_ENABLED: false

##################################  Chronyd 时间同步设置 ###########################
## 时间同步服务器IPS,如果有多个请填多个
# eg: TIME_SERVER: ["localhost"] TIME_SERVER: ["localhost","127.0.0.1"]
TIME_SERVER: ["localhost","127.0.0.1"]

##################################  RunTime 配置 #################################
# runtime 选择，目前只支持docker，未适配containerd
RUNTIME_TYPE: docker

##################################  Docker 配置  #################################
# Docker版本,已验证版本: 
DOCKER_VERSION: 20.10.24

# Docker 数据目录
DOCKER_ROOT_DATA: /var/lib/docker

# Docker driver版本(systemd|cgroupfs)
# tips: Docker版本>=20.10才能使用systemd驱动
DOCKER_DRIVER: systemd

# docker网段设置(如有网络冲突，可自行修改,一般默认即可)
DOCKER_BIP: 192.168.244.1/24

#Docker INSECURITY配置，默认为Harbor域名
DOCKER_INSECURITY: otter.harbor.com

# Docker Remote API是否开启
DOCKER_REMOTE_API_ENABLE: false

################################ Containerd 配置(暂时未适配) #######################


################################ K8S 配置   #######################################
# k8s 版本
KUBERNETES_VERSION: 1.20.8

# pod网段设置(如有网络冲突，可自行修改,一般默认即可) 
POD_NETWORK_CIDR: 10.244.0.0/16

# service 网段(如有网络冲突，可自行修改，一般默认即可)
SERVICE_CIDR: 10.96.0.0/12

# k8s网络模式(默认启用ipvs,当缺少ipvs模块时，启动切换iptables)
KUBERNETES_NETWORK_MODEL: ipvs

# k8s cni插件类型(flannel|calico|),暂时只支持flannel
KUBERNETES_CNI_TYPE: flannel

# k8s etcd数据目录(如有单独磁盘供etcd使用，可修改该路径-在安装前修改)
KUBERNETES_ETCD_DATA_DIR: /var/lib/etcd

# k8s deschduler组件是否部署
KUBERNETES_DESCHDULER_ENABLE: false

# k8s VIP，当K8S高可用时,node节点将基于lvscare，使用这个VIP与APIserver通信
# 当节点数<=3时，可不用填
KUBERNETES_VIP: 127.0.0.1

# k8s init token(设置默认的bootstrap token)
KUBERNETES_BOOTSTRAP_TOKEN: xxb12jk1234debxkfcbxae9d876641c8


################################ Harbor 配置  ####################################
# 是否部署HARBOR，HARBOR部署方式为Chart部署,我们默认推荐部署
HARBOR_ENABLE: true

# Harbor 域名,如果没有域名需求默认即可
HARBOR_DOMAIN: otter.harbor.com

# HARBOR 部署节点IP，该IP必须要是K8S集群内
HARBOR_IP: 127.0.0.1

# Harbor 访问Port
HARBOR_PORT: 443

# Harbor admin登陆密码
HARBOR_PASSWORD: Otter007

# Harbor 数据目录
HARBOR_DATA_PATH: /data/harbor