- name: Disable Selinux
  shell: setenforce 0 | cat

- name: Disable Selinux Configuration
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Disable Firewalld
  systemd: name=firewalld enabled=no state=stopped

- name: Disable NetworkManager
  systemd: name=NetworkManager state=stopped enabled=no
  when: ansible_distribution_major_version|int == 7

# 配置Yum源
- name: Distribute Yum Repo Configuration
  copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }} force=yes
  with_items:
  - yum/centos7/Centos7-epel.repo
  - yum/centos7/Centos7.repo
  when: ansible_distribution_major_version|int == 7

- name: Distribute Yum Repo Configuration
  copy: src=yum/centos8/Centos8.repo dest=/etc/yum.repos.d/Centos8.repo force=yes
  when: ansible_distribution_major_version|int == 8

# 安装基础软件
- name: Install Basic Software For System
  shell: yum -y install {{ ONLINE['CENTOS7_SOFTWARE'] }} | join(" ") }} | cat
  when: 
  - OTTER_INSTALL_METHOD|string == "online"
  - ansible_distribution_major_version|int == 7

- name: Install Basic Software For System
  shell: yum -y install {{ ONLINE['CENTOS8_SOFTWARE'] | join(" ") }} | cat
  when: 
  - OTTER_INSTALL_METHOD|string == "online"
  - ansible_distribution_major_version|int == 8

## todo 离线包