- name: Disable Selinux
  shell: setenforce 0 | cat

- name: Disable Selinux Configuration
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Disable Firewalld
  systemd: name=firewalld enabled=no state=stopped

- name: Disable NetworkManager
  systemd: name=NetworkManager state=stopped enabled=no
  when: 
  - ansible_distribution_major_version|int == 7
  - ansible_distribution == "CentOS"

# 备份原yum文件
- block:
  - name: Get All Yum Repo Files
    find: paths=/etc/yum.repos.d file_type=file 
    register: yum_repo_files
  
  - name: Create Yum Repo Backup Directory
    file: path=/etc/yum.repos.d/yum-backup state=directory mode=0755
  
  - name: Copy Yum Repo Files to /etc/yum.repos.d
    copy: src={{ item.path }} dest=/etc/yum.repos.d/yum-backup/{{ item.path | basename }} remote_src=yes mode=0755
    loop_control:
      label: "{{ item.path | basename }}"
    with_items: "{{ yum_repo_files.files }}"

  - name: Delete Yum Repo Files
    file: path={{ item.path }} state=absent
    loop_control:
      label: "{{ item.path | basename }}"
    with_items: "{{ yum_repo_files.files }}"


# 配置Yum源
- block:
  - name: Distribute Yum Repo Configuration
    copy: src={{ item }} dest=/etc/yum.repos.d/{{ item.split('/') | last }}
    loop_control:
      label: "{{ item.split('/') | last }}"
    with_items:
    - yum/centos7/otter-centos7-epel.repo
    - yum/centos7/otter-centos7.repo
    when: 
    - ansible_distribution_major_version|int == 7
    - ansible_distribution == "CentOS"
  
  - name: Distribute Yum Repo Configuration
    copy: src={{ item }} dest=/etc/yum.repos.d/{{ item.split('/') | last }}
    loop_control:
      label: "{{ item.split('/') | last }}"
    with_items:
    - yum/centos8/otter-centos8-epel-modular.repo
    - yum/centos8/otter-centos8-epel-testing-modular.repo
    - yum/centos8/otter-centos8-epel-testing.repo
    - yum/centos8/otter-centos8-epel.repo
    - yum/centos8/otter-centos8.repo
    when: 
    - ansible_distribution_major_version|int == 8
    - ansible_distribution == "CentOS"
  
  - name: Distribute Yum Repo Configuration
    copy: src={{ item }} dest=/etc/yum.repos.d/{{ item.split('/') | last }}
    loop_control:
      label: "{{ item.split('/') | last }}"
    with_items:
    - yum/rocky9/otter-rocky9-addons.repo
    - yum/rocky9/otter-rocky9-devel.repo
    - yum/rocky9/otter-rocky9-epel-testing.repo
    - yum/rocky9/otter-rocky9-epel.repo
    - yum/rocky9/otter-rocky9-extras.repo
    - yum/rocky9/otter-rocky9.repo
    when: 
    - ansible_distribution_major_version|int == 9
    - ansible_distribution == "Rocky"

# 安装基础软件
- block:
  - name: Install Basic Software For System
    yum: name={{ ONLINE['CENTOS7_SOFTWARE'] }} state=present update_cache=yes
    when: 
    - OTTER_INSTALL_METHOD|string == "online"
    - ansible_distribution_major_version|int == 7
    - ansible_distribution == "CentOS"
  
  - name: Install Basic Software For System
    yum: name={{ ONLINE['CENTOS8_SOFTWARE'] }} state=present update_cache=yes
    when: 
    - OTTER_INSTALL_METHOD|string == "online"
    - ansible_distribution_major_version|int == 8
    - ansible_distribution == "CentOS"
  
  - name: Install Basic Software For System
    yum: name={{ ONLINE['ROCKY9_SOFTWARE'] }} state=present update_cache=yes
    when: 
    - OTTER_INSTALL_METHOD|string == "online"
    - ansible_distribution_major_version|int == 9
    - ansible_distribution == "Rocky"

## todo 离线包
#shell: yum -y install {{ ONLINE['CENTOS8_SOFTWARE'] | join(" ") }} | cat