- name: Disable Selinux
  shell: setenforce 0 | cat

- name: Disable Selinux Configuration
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Disable Firewalld
  systemd: name=firewalld enabled=no state=stopped

- name: Disable NetworkManager
  systemd: name=NetworkManager state=stopped enabled=no
  when: 
  - ansible_distribution == "CentOS"
  - ansible_distribution_major_version|int == 7