---
- name: Create Temp Directory for otter
  file: path=/tmp/otter state=directory mode=0755 recurse=yes 

- name: Turn Off Swap
  shell: swapoff -a

- name: Disable Swap
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes

- name: Configuration ulimit Configuration
  copy: src=k8s-ulimits.conf dest=/etc/security/limits.d/k8s-ulimits.conf

- name: Kernel Parameter Optimization
  sysctl: name={{ item.name }} value={{ item.value }} state=present sysctl_file=/etc/sysctl.conf ignoreerrors=yes
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: yes
  with_items: "{{ KERNEL_PARAMETER }}"