- name: System Optimization for ALL System
  include_tasks: common.yaml

- name: System Optimization for Centos
  include_tasks: centos.yaml
  when: ansible_distribution == "CentOS"

- name: System Optimization for Ubuntu
  include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"