## todo 
# fix: 为每个节点创建离线资源包文件夹,otterdownload mkdir it
# 1. 节点时区设置

- name: System Optimization for ALL System
  include_tasks: common.yaml

- name: System Optimization for Centos
  include_tasks: centos.yaml
  when: ansible_distribution == "CentOS"

- name: System Optimization for Rocky
  include_tasks: centos.yaml
  when: ansible_distribution == "Rocky"

- name: System Optimization for Ubuntu
  include_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"