- name: Deploy Flanel for Kubernetes 
  include_tasks: kube-flannel-v0.21.4.yaml
  when: KUBERNETES_VERSION.split('.')[0:2]|join('.')|float >= 1.25

- name: Deploy Flanel for Kubernetes 
  include_tasks: kube-flannel-v0.18.1.yaml
  when: KUBERNETES_VERSION.split('.')[0:2]|join('.')|float < 1.25