- hosts:
  - kubernetes_cluster
  ignore_unreachable: false
  roles: 
  - { role: runtime/docker, tags: docker, when: RUNTIME_TYPE|string == "docker" }
  - { role: runtime/containerd, tags: containerd, when: RUNTIME_TYPE|string == "containerd" }