- hosts:
  - kubernetes_master
  ignore_unreachable: false
  vars_files:
  - ../config/otter.yaml
  - ../config/middleware/harbor.yaml
  - ../config/middleware/monitor.yaml
  roles: 
  - { role: kubernetes/kubernetes-master, tags: kubernetes-master }