- hosts:
  - kubernetes_master
  ignore_unreachable: false
  vars_files:
  - ../config/otter.yaml
  - ../config/middleware/harbor.yaml
  - ../config/middleware/monitor.yaml
  roles: 
  - {role: otter-test, tags: test }
  #- { role: cni/flannel, tags: flannel }
  #- { role: k9s, tags: k9s}
  #- { role: helm, tags: helm }
  #- { role: cni/flannel, tags: cni-flannel-test }